"""empty message

Revision ID: 7af90ca55b8f
Revises: 70734ece2af0
Create Date: 2019-05-12 22:37:43.480163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af90ca55b8f'
down_revision = '70734ece2af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('addr', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pin', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
