"""empty message

Revision ID: e54aad24bb4c
Revises: 33ab40f5bdfa
Create Date: 2019-05-13 23:10:14.087015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54aad24bb4c'
down_revision = '33ab40f5bdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('registered_on', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('credit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_company', sa.VARCHAR(length=255), nullable=False),
    sa.Column('num_company', sa.VARCHAR(length=255), nullable=False),
    sa.Column('credit', sa.FLOAT(), nullable=False),
    sa.Column('registered_on', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_company')
    )
    # ### end Alembic commands ###
